### ISSUE TITLE
What document do I need to change for version up?

### ISSUE THREAD

**Issue by hiroyuki-sato** [test-unit/test-unit.github.io#12]
Hello, 

The latest [test-unit-rails](http://test-unit.github.io) version is incorrect. (5.0.5 -> 5.1.3).
What document do I need to change for version up?

I will create PR.
Thank you.

**Comment by kou** [comment]
Thanks.
We need to update https://github.com/test-unit/test-unit.github.io/blob/master/_config.yml .

**Comment by hiroyuki-sato** [comment]
Thank you!

I created #13. PTAL.
