### ISSUE TITLE
リファレンスマニュアルへのリンク切れ

### ISSUE THREAD

**Issue by sunnyone** [test-unit/test-unit.github.io#2]
Webページの中の各種マニュアルへのリンクが切れています。

https://test-unit.github.io/ja/
- test-unit 1.2.3のリファレンスマニュアル
- リファレンスマニュアル (test-unit-capybaraのドキュメント の中)
- リファレンスマニュアル (test-unit-notifyのドキュメント の中)

https://test-unit.github.io/test-unit/ja/
- doc/text/how-to.md

**Comment by rhysd** [comment]
en/ja 共に how-to.md へのリンクが切れているようです．

http://test-unit.github.io/test-unit/en/
http://test-unit.github.io/test-unit/ja/

**Comment by kou** [comment]
「link for GitHub」の方だけですよね？「link for YARD」の方は切れていませんよね？

GitHubのMarkdownの扱いとYARDのMarkdownの扱いが異なるので、同じマークアップでGitHubのページとYARDで生成したHTMLで正しいリンクを作れません。なので、両方用意しています。

**Comment by rhysd** [comment]
はい，GitHub のほうだけです．
なるほど，そういう仕様でしたか．ありがとうございます．
