### ISSUE TITLE
`https://test-unit.github.io/ja/` の更新方法について

### ISSUE THREAD

**Issue by kachick** [test-unit/test-unit.github.io#39]
(日本語ドキュメントについての質問が多く含まれるので、日本語で書かせていただきます 🙇 )

https://groups.google.com/g/test-unit-commit へのリファレンスが貼られているのですが、 2017 年が最後のメールになっているようで現在有効な情報では無いのでしょうか？

https://github.com/search?q=org%3Atest-unit+%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%BC%E3%83%AB&type=code

を見ると

<img width="1096" alt="screen_shot 2021-06-06 19 10 06" src="https://user-images.githubusercontent.com/1180335/120920651-d30e8580-c6fa-11eb-85ae-3426ad694d7e.png">

このリポジトリにしか情報がないようです。(GitHub の日本語検索があてにならないというのはあるので、ちょっと自信がないですが)

また、 html は https://github.com/test-unit/test-unit.github.io/pull/36 の様に、自動生成されているのかなと理解しているのですが。(一応記載されている方法を自分のローカルで試したがうまくいきませんでした・・・)

https://github.com/test-unit/test-unit.github.io/blob/7c3ff59463087e58f5491f9e053f8fd76bdfdbe9/ja/index.html#L41

こういった Ruby 2.2 前の情報等、この html 以外のどこに生成元ファイルがあるのかが見つけられませんでした。

---

* test-unit の 最新情報等を追うおすすめの方法があれば教えていただけると助かります 🙇 
* http://test-unit.github.io/ を 更新する好ましい方法はどういったものでしょうか？(現在 3.4.4 が最新版だと思うのですが、サイトが 3.4.1 なので・・・)

**Comment by hiroyuki-sato** [comment]
ドキュメントは、ディレクトリが以下のようになっていることを前提としています。

* 今`test-unit`本体とhttp://test-unit.github.io/を更新するのが別の人になっていいるので、更新にタイムラグがあります。
* cloneするリポジトリを下記ような構成にすると #36 のようにドキュメントの生成ができると思います。
* test-unitの日本語ドキュメントは[これ](https://github.com/test-unit/test-unit/blob/master/doc/po/ja.po)をソースにして生成されています。
* test-unitの最新情報はtest-unitのリポジトリをみるか、[kou](https://twitter.com/ktou) さんに聞くのが良いと思います。
* 補足や修正事項があればお願いします。> @kou


ディレクトリ構成

```
gems/test-unit
www/test-unit.github.io/
```

**Comment by kachick** [comment]
おぉ！早速ありがとうございます！大変助かります！ 🙏 

https://github.com/test-unit/test-unit.github.io/pull/40 で早速 3.4.4 への update もしていただけたようでありがとうございます！ 🙏

**Comment by kou** [comment]
コミットメールは https://www.commit-email.info/ に移動しました。
今は`test-unit@ml.commit-email.info`を使っています。更新していなくてすみません。。。

> こういった Ruby 2.2 前の情報等、この html 以外のどこに生成元ファイルがあるのかが見つけられませんでした。

トップレベルにある`test-unit`から始まるディレクトリー以外はここのリポジトリーにあるファイルがマスターです。なので、このリポジトリーにあるファイルを更新します。

test-unitの最新情報は https://github.com/test-unit/test-unit/blob/master/doc/text/news.md / https://test-unit.github.io/test-unit/en/file.news.html のつもりです。が、だいたい1行説明なので情報が足りないかもしれません。。。足りないときは「これじゃわかんない。。。」と教えてください。。。
（メソッドのドキュメントは私にしては書いている方なので適切なドキュメントにちゃんとリンクを張るようにしたほうがいい気がしますね。。。）

test-unitのドキュメントの生成は https://github.com/ruby/csv/blob/master/.github/workflows/test.yml#L96-L135 みたいに自動生成にしちゃった方がいいかもしれませんね。。。ここの`_config.yml`の更新はしなくちゃいけないんですが、リファレンス生成がなくなれば更新が楽になるとは思います。

**Comment by kachick** [comment]
教えていただいてありがとうございます！ 🙏 

>test-unitの最新情報は https://github.com/test-unit/test-unit/blob/master/doc/text/news.md / https://test-unit.github.io/test-unit/en/file.news.html

前から欲しかった assert_raise_with_message が追加されたこと や https://github.com/test-unit/test-unit/blob/2ab0012796d135a9c8564e47172d037514c9325e/doc/text/news.md#329---2018-12-01-version-3-2-9 の data driven test の詳細など大変参考になってます 🙏 

>自動生成

なるほどです。

https://github.com/test-unit/test-unit.github.io/issues/39#issuecomment-855399374

に書いていただいたディレクトリ構成にしたら確かに生成出来てバンザイ！という感じだったのですが、 

`gems/test-unit` 側の `doc/po/ja.po` にも update がかかるようで、これはこれでPRを出していったほうが良いんですかね。 (妥当そうな diff には見えました。)
そうなると、自動生成時にはそちらの update も本当はした方が良いということになり、ちょっと難しい・・・？ 🤔

いずれにせよ大変助かりました。何か自分でも更新できそうなドキュメントを見つけたら、今後は教えていただいた方法でトライしてみますね！
